import { ModalProvider } from "../components/Providers/ModalProvider";
import "../globals.css";

import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={``}>
        <body className="">
          <ModalProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
